# Generated by Django 3.0.3 on 2022-02-09 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.Product'),
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.Purchase'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.Provider'),
        ),
        migrations.AddField(
            model_name='promotionsdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.Product'),
        ),
        migrations.AddField(
            model_name='promotionsdetail',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Promotions'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.Category', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='paymentsdebtspay',
            name='debtspay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.DebtsPay'),
        ),
        migrations.AddField(
            model_name='paymentsctacollect',
            name='ctascollect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.CtasCollect'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='typeexpense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.TypeExpense', verbose_name='Tipo de Gasto'),
        ),
        migrations.AddField(
            model_name='debtspay',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.Purchase'),
        ),
        migrations.AddField(
            model_name='ctascollect',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.Sale'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
